=== goochjs/mule-splitter-aggregator/src/test/resources/xml/item-v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns="http://schemas.goochjs.org/item-v1"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:itm="http://schemas.goochjs.org/item-v1"
	targetNamespace="http://schemas.goochjs.org/item-v1"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Item">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Thing" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Description" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="anything"/>
									<xs:enumeration value="something"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="sequence" type="xs:integer" use="optional"/>
			<xs:attribute name="action" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="create"/>
						<xs:enumeration value="read"/>
						<xs:enumeration value="update"/>
						<xs:enumeration value="delete"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ItemList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== goochjs/mule-splitter-aggregator/src/test/resources/xml/ItemList.xml
<?xml version="1.0" encoding="UTF-8"?>
<ItemList
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://schemas.goochjs.org/item-v1">
		
	<itm:Item sequence="1" action="create"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:itm="http://schemas.goochjs.org/item-v1"
		xsi:schemaLocation="http://schemas.goochjs.org/item-v1 item-v1.xsd">
		<itm:Thing type="something">
			<itm:Description>Something</itm:Description>
		</itm:Thing>
		
		<itm:Thing type="anything">
			<itm:Description>Something else</itm:Description>
		</itm:Thing>
	</itm:Item>
	
	<itm:Item sequence="2" action="update"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:itm="http://schemas.goochjs.org/item-v1"
		xsi:schemaLocation="http://schemas.goochjs.org/item-v1 item-v1.xsd">
		<itm:Thing type="anything">
			<itm:Description>A wotsit</itm:Description>
		</itm:Thing>
	</itm:Item>
	
	<itm:Item sequence="2" action="create"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:itm="http://schemas.goochjs.org/item-v1"
		xsi:schemaLocation="http://schemas.goochjs.org/item-v1 item-v1.xsd">
		<itm:Thing type="something">
			<itm:Description>A doohinky</itm:Description>
		</itm:Thing>
	</itm:Item>
	
	<itm:Item sequence="3" action="delete"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:itm="http://schemas.goochjs.org/item-v1"
		xsi:schemaLocation="http://schemas.goochjs.org/item-v1 item-v1.xsd">
		<itm:Thing type="something">
			<itm:Description>A different doohinky</itm:Description>
		</itm:Thing>
	</itm:Item>
</ItemList>

=== goochjs/mule-splitter-aggregator/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<itm:ItemList
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:itm="http://schemas.goochjs.org/item-v1"
		xsi:schemaLocation="http://schemas.goochjs.org/item-v1 item-v1.xsd">
		
	<itm:Item sequence="1" action="create">
		<itm:Thing type="something">
			<itm:Description>Something</itm:Description>
		</itm:Thing>
		
		<itm:Thing type="anything">
			<itm:Description>Something else</itm:Description>
		</itm:Thing>
	</itm:Item>
	
	<itm:Item sequence="2" action="update">
		<itm:Thing type="anything">
			<itm:Description>A wotsit</itm:Description>
		</itm:Thing>
	</itm:Item>
	
	<itm:Item sequence="2" action="create">
		<itm:Thing type="something">
			<itm:Description>A doohinky</itm:Description>
		</itm:Thing>
	</itm:Item>
	
	<itm:Item sequence="3" action="delete">
		<itm:Thing type="something">
			<itm:Description>A different doohinky</itm:Description>
		</itm:Thing>
	</itm:Item>
</itm:ItemList>
